### ISSUE TITLE
  Hello, can you share your model

### ISSUE THREAD

**Issue by wuxiaolianggit** [adobe-research/MakeItTalk#1]
Hello, can you share your model？
                @macdonst

**Comment by ZerRui** [comment]
Thank you for such an excellent project. It is amazing. Can you share your model? Thank you!

**Comment by dingzeyuli** [comment]
Hi @wuxiaolianggit and @ZerRui,

Thanks for your interests! In the coming weeks, we plan to improve the code/documentation and release the model. Please stay tuned!

**Comment by wayneszq** [comment]
Hi, the result looks great, thanks for sharing.

Can you please share the pre-trained weight files first? 

many thanks.

**Comment by xupp1989** [comment]
Hi, Great works!

Could you share the pre-trained weights?

thanks.

**Comment by ghost** [comment]
@dingzeyuli the links in the updated fork for pretrained models are not working https://github.com/yzhou359/MakeItTalk

**Comment by agangzz** [comment]
@dingzeyuli I also find that the links in the updated fork for pretrained models are not working https://github.com/yzhou359/MakeItTalk

Could you re-updated the pretrained models? thanks

**Comment by ShenhanQian** [comment]
Congrats on this awesome work!
Would you please leave a timeline for the release of trained models and training scripts? Thank you in advance!

One more thing, I found that `Issues` is not turned on in [https://github.com/yzhou359/MakeItTalk](https://github.com/yzhou359/MakeItTalk).

**Comment by yzhou359** [comment]
Pre-trained model links are updated and `Issues` in [https://github.com/yzhou359/MakeItTalk](https://github.com/yzhou359/MakeItTalk) is turned on.
