### ISSUE TITLE
about the facewarp.exe

### ISSUE THREAD

**Issue by VolcanoBin** [adobe-research/MakeItTalk#16]
How can I change the details of facewarp.exe? Or where I can get the source code?Thanks.

**Comment by dingzeyuli** [comment]
The source code for facewarp is in https://github.com/adobe-research/MakeItTalk/tree/main/facewarp/facewarp, along with build instructions.

**Comment by VolcanoBin** [comment]
那个dingwarp呢？就是我跑https://github.com/yzhou359/MakeItTalk这个代码之后，合成动画视频的过程中，会弹出dingwarp的一个一帧帧播放的窗口，我想问这个窗口能关掉吗？我问facewarp.exe的源码就是想看看能不能关掉这里。生成视频的时间太长了

**Comment by VolcanoBin** [comment]
> The source code for facewarp is in https://github.com/adobe-research/MakeItTalk/tree/main/facewarp/facewarp, along with build instructions.

那个dingwarp呢？就是我跑https://github.com/yzhou359/MakeItTalk
这个代码之后，合成动画视频的过程中，会弹出dingwarp的一个一帧帧播放的窗口，我想问这个窗口能关掉吗？我问facewarp.exe的源码就是想看看能不能关掉这里。生成视频的时间太长了

**Comment by twb1235** [comment]
你好，请问你找到方法可以关掉dingwarp窗口吗。
