### ISSUE TITLE
No AutoVC in third party 

### ISSUE THREAD

**Issue by kryzhikov** [adobe-research/MakeItTalk#6]
Hi! 
Thanks for a great project! 
Wanted to try the Colab demo, but found out that there is nо Autovc utils in thirdparty directory.  And in is actually in src 
So the line should be changed to 
```
from src.approaches.train_image_translation import Image_translation_block
```
<img width="1169" alt="Снимок экрана 2020-11-08 в 22 36 47" src="https://user-images.githubusercontent.com/17138280/98482495-e4e68380-2212-11eb-9dc9-171b215ce385.png">

**Comment by yzhou359** [comment]
Thanks for finding this out. You're correct and we've fixed that in the latest commit.
